site_name: SkyMapper
site_description: Commercial UAV-Smart Phone Integration for Low-Cost 3D Reconstruction
site_author: Nojin Park, Ji Hyun Seo, Byounghyun Yoo

theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.indexes
  palette:
    scheme: slate

# 마크다운 확장 기능 (버튼 디자인 등을 위해 필요)
markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: guide/index_2.md
  - Hardware Setup: guide/hardware.md
  - Software Setup: guide/software.md